// Books
export const REQUEST_ALL_BOOKS = 'REQUEST_ALL_BOOKS';
export const SUCCESS_ALL_BOOKS = 'SUCCESS_ALL_BOOKS';
export const ERROR_ALL_BOOKS = 'ERROR_ALL_BOOKS';
export const REQUEST_DELETE_BOOK = 'REQUEST_DELETE_BOOK';
export const SUCCESS_DELETE_BOOK = 'SUCCESS_DELETE_BOOK';
export const ERROR_DELETE_BOOK = 'ERROR_DELETE_BOOK';