// Book
export const REQUEST_ONE_BOOK = 'REQUEST_ONE_BOOK';
export const SUCCESS_ONE_BOOK = 'SUCCESS_ONE_BOOK';
export const ERROR_ONE_BOOK = 'ERROR_ONE_BOOK';

export const REQUEST_CREATE_BOOK = 'REQUEST_CREATE_BOOK';
export const SUCCESS_CREATE_BOOK = 'SUCCESS_CREATE_BOOK';
export const ERROR_CREATE_BOOK = 'ERROR_CREATE_BOOK';

export const REQUEST_EDIT_BOOK = 'REQUEST_EDIT_BOOK';
export const SUCCESS_EDIT_BOOK = 'SUCCESS_EDIT_BOOK';
export const ERROR_EDIT_BOOK = 'ERROR_EDIT_BOOK';
